### ISSUE TITLE
To restrict user input in fields according to Character Limit

### ISSUE THREAD

**Issue by jayrdi** [statamic/ideas#1017]
I'm trying to restrict the number of chars a user can enter for an article summary to display on an index card.

I have the fieldtype "textarea" with the "character limit" set to 150.

If you go into the News Article it allows you to enter more than 150 chars though, and the char counter under the window just displays e.g. 167/150 in red.

I know that users will ignore this char counter and just enter whatever they like! So, could we implement this as a feature to restrict a user entering more characters than have been set my the limit in the Blueprint?

**Comment by joshuablum** [comment]
Hey @jayrdi,

That's what [validation rules](https://statamic.dev/validation) are for. Just set it to `max:150` for the article summary in the Blueprint and your users won't be able to save the entry if the summary exceeds 150 characters. 
<img width="1238" alt="image" src="https://github.com/statamic/ideas/assets/3824203/ad923afe-f27b-45e7-864f-2d1d545e1fee">
<img width="811" alt="image" src="https://github.com/statamic/ideas/assets/3824203/d0bf6edb-da75-4655-b276-ca5c41875443">

**Comment by jayrdi** [comment]
@joshuablum that's perfect, thanks a lot!

**Comment by jayrdi** [comment]
@joshuablum oh, actually I tried that and it still lets me save...

So, I have the fieldtype set to "character limit" of 150 and under validation I have set "max:150". In the `article_summary` the char counter goes red when it exceeds 150 but still lets me save. Is this because I'm running a local build at the moment?

**Comment by joshuablum** [comment]
@jayrdi Tried it locally (took the screenshots then) and it doesn't let me save and works as intended. Make sure to clear the caches and do a hard refresh in your browser.

That's the relevant part of the Blueprint:
```yaml
handle: article_summary
    field:
        character_limit: '150'
        antlers: false
        type: textarea
        display: 'Article summary'
        icon: textarea
        listable: hidden
        instructions_position: above
        visibility: visible
        hide_display: false
        validate:
          - 'max:150'
```
