### ISSUE TITLE
Allow access to underlying asset data in asset blueprint fields

### ISSUE THREAD

**Issue by daun** [statamic/ideas#1136]
It'd be great to get access to the underlying asset data in custom field conditions of asset blueprints. Currently, we only get access to the values of other fields in the same blueprint.

Example: only show an `autoplay` toggle in the asset blueprint if the `path` of the asset ends with `.mp4` — this is currently not possible as the custom field conditions do not have access to `width`, `height`, `path`, etc.

```yaml
fields:
  -
    handle: autoplay
    field:
      type: toggle
      display: Autoplay
      inline_label: Autoplay
      inline_label_when_true: Autoplay
      if:
        this: 'custom video'
```
