### ISSUE TITLE
Hidden collections appear on certain pages?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/ideas#1304]
Hi, 

I've setup an `editor` role, the role has access to _some_ collections. If I impersonate or login as an editor and navigate away from `/cp/collections` the hidden collections are shown in the sidebar? The hidden collections are in a section called `bones`.

https://github.com/user-attachments/assets/409408f0-0e9a-4b5d-b3fa-e91dcb4721d4

```
editor:
  title: Editor
  permissions:
    - 'access cp'
    - 'view pages entries'
    - 'edit pages entries'
    - 'create pages entries'
    - 'delete pages entries'
    - 'publish pages entries'
    - 'reorder pages entries'
    - 'edit other authors pages entries'
    - 'publish other authors pages entries'
    - 'delete other authors pages entries'
    - 'view products entries'
    - 'edit products entries'
    - 'create products entries'
    - 'delete products entries'
    - 'publish products entries'
    - 'reorder products entries'
    - 'edit other authors products entries'
    - 'publish other authors products entries'
    - 'delete other authors products entries'
    - 'view case_studies entries'
    - 'edit case_studies entries'
    - 'create case_studies entries'
    - 'delete case_studies entries'
    - 'publish case_studies entries'
    - 'reorder case_studies entries'
    - 'edit other authors case_studies entries'
    - 'publish other authors case_studies entries'
    - 'delete other authors case_studies entries'
    - 'view blog entries'
    - 'edit blog entries'
    - 'create blog entries'
    - 'delete blog entries'
    - 'publish blog entries'
    - 'reorder blog entries'
    - 'edit other authors blog entries'
    - 'publish other authors blog entries'
    - 'delete other authors blog entries'
    - 'view main_menu nav'
    - 'edit main_menu nav'
    - 'view legal_menu nav'
    - 'edit legal_menu nav'
    - 'view categories terms'
    - 'edit categories terms'
    - 'create categories terms'
    - 'delete categories terms'
    - 'view assets assets'
    - 'upload assets assets'
    - 'edit assets assets'
    - 'move assets assets'
    - 'rename assets assets'
    - 'delete assets assets'
    - 'view updates'
    - 'access cache utility'
  preferences:
    start_page: collections/pages
    favorites: {  }
```

Version
```
Environment
Application Name: Bones
Laravel Version: 11.39.1
PHP Version: 8.3.8
Composer Version: 2.6.5
Environment: local
Debug Mode: OFF
URL: bones.test
Maintenance Mode: OFF
Timezone: Europe/London
Locale: en_GB

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.46.0 PRO

Statamic Addons
jonassiewertsen/statamic-jobs: 1.5.0
statamic/importer: 1.7.2
visuellverstehen/statamic-anchor-navigation: 1.0.0
```
