### ISSUE TITLE
Set default filters?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/ideas#1305]
Hi

Is there a way to set default filters for all users? I'd like to show All, Draft and Published as default filters for all users. 

<img width="261" alt="Image" src="https://github.com/user-attachments/assets/e87254a1-bccb-4360-af22-c4d92e47200d" />

```
preferences:
  collections:
    blog:
      after_save: continue_editing
      filters:
        draft:
          display: Draft
          filters:
            status:
              status: draft
        published:
          display: Published
          filters:
            status:
              status: published
    case_studies:
      filters:
        draft:
          display: Draft
          filters:
            status:
              status: draft
        published:
          display: Published
          filters:
            status:
              status: published
```

**Comment by duncanmcclean** [comment]
You can create a `resources/preferences.yaml` file containing any preferences you'd like to be the default for all users.

For example:

```yaml
# resources/preferences.yaml

collections:
    blog:
      after_save: continue_editing
      filters:
        draft:
          display: Draft
          filters:
            status:
              status: draft
```
