### ISSUE TITLE
v3 Content API - Filtering by Relationship

### ISSUE THREAD

**Issue by philsturgeon** [statamic/ideas#138]
The Entries Endpoint has filter which only allows filtering on fields within that resource. It would be exceptionally handy if I could filter on related resources.

```
/api/collections/actions/entries/?filter[categories:slug:is]=waste
```

The action blueprint has a relationship for many categories:

```yaml
# api/resources/blueprints/action.yaml

           - handle: categories
              field:
                  max_items: 3
                  mode: select
                  collections:
                      - categories
                  type: entries
                  instructions: "Ideally most actions would fit in one or two categories, if it's more than that maybe see if they have sub-pages to add as their own actions."
                  localizable: false
                  width: 50
                  listable: hidden
                  display: Categories
```
