### ISSUE TITLE
Ability to attach meta-data to nav items

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#169]
In our V2 site builder we have the ability to make navigation (via global) and we attach some fields to it:
```yaml
        -
          link_type: link
          link_url: 'http://foobar.com'
          link_text: 'sub item 1'
          link_class: 'class1 class2'
```

The `link_text` is now `title` which is fine, but how can we attach styling to the that nav item?

Perhaps attach a fieldset to a nav item?
