### ISSUE TITLE
Override fieldset options when linked in another fieldset

### ISSUE THREAD

**Issue by padders** [statamic/ideas#197]
I'd like to use fieldsets to create options for things like padding or colour options. So I create a fieldset for padding, and then add that fieldset to another allowing me to add padding options to any element in the editor. I can reuse the padding fieldset anywhere meaning I only have to update the config for it once.

What would be brilliant is being able to override certain things like the default value (which as an aside is also missing in the front end, you can add placeholder text, but not the default. You have to add that manually in the Yaml currently), and the width (in the front end) to make it fit in that particular fieldsets editor better

**Comment by jasonvarga** [comment]
You can override config when you import individual fields.

**Comment by padders** [comment]
Hmmm, I must be doing something wrong then. I have a fieldset below

```
title: 'Snippet - Text Colour'
fields:
  -
    handle: text_colour
    field:
      options:
        text-white: white
        text-black: black
        text-rm-yellow: yellow
      clearable: false
      multiple: false
      searchable: true
      taggable: false
      push_tags: false
      cast_booleans: false
      type: select
      localizable: false
      width: 50
      listable: hidden
      display: 'Text colour'
```

I add that to another fieldset where I want the colour options on a certain text field. I do that using

```
title: 'Hero - Full Screen Image with text'
fields:
   -
    import: snippet-_text_colour
    prefix: subtitle_
```

If I add change it to the following I still have no default, and the width is still 50.

```
title: 'Hero - Full Screen Image with text'
fields:
   -
    import: snippet-_text_colour
    prefix: subtitle_
    width: 100
    default: 'text-white'
```

**Comment by jasonvarga** [comment]
You're importing the whole fieldset. You can only override configuration when you import (reference) _individual fields_.

```
-
  handle: myfield
  field: somefieldset.somefield
  config:
    width: 100
```

**Comment by padders** [comment]
Ahhhhh, Thank you.

Figured I must have been doing something stupid :)

**Comment by padders** [comment]
Just wondering if it's possible to add a prefix when you import a field only? We'd like to use text colour on multiple fields in the same fieldset! The control panel doesn't seem to allow this and adding the code below didn't do anything

```
  -
    handle: text_colour
    field: snippet-_text_colour.text_colour
    prefix: header_
    config:
      options:
        text-white: white
        text-black: black
        text-rm-yellow: yellow
```
