### ISSUE TITLE
Content Factories with Faker

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#203]
Implementation of content factories using Faker, similar to Laravel Model Factories. This would be great to quickly whip up fake collection entries, taxonomies etc. for development and testing. The factory could be based on the linked Blueprints.

The Faker generator to use for each field could be defined with a `faker` key:
```yaml
title: Default
sections:
  main:
    display: Main
    fields:
      -
        handle: name
        field:
          display: 'Name'
          faker: name
          type: text
```

This could also be an addon. I started working on a proof of concept for `v3`. I'm currently stuck on creating an entry.  I found the `Entry::make()` method. But this just creates a blank entry with no values for things like `id` and the like. Wondering if there's going to be an `API` to create entries with some passed on data.
