### ISSUE TITLE
Make fieldtype config fields extendable

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#206]
I'm working on an addon that's looking for certain keys defined on stock fieldtypes in a blueprint. It would be awesome to be able to extend the blueprint builder in the CP to allow for custom options. This way, the user can define the options through the UI rather than hacking the blueprint yaml.

## Example
Make it possible to set the value for the key `factory` on the `text` fieldtype through its options in the blueprint builder.

```yaml
title: Factory
sections:
  main:
    display: Main
    fields:
      -
        handle: name
        field:
          type: text
          factory: firstName
```
