### ISSUE TITLE
Allow for content variables in blueprint

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#235]
I'd like to be able to pass a content variable to a blueprint field. Similar to have you can use `{env:VARIABLE}` in the settings in v2.

```md
# product.md
id: 8a0a4e4e-2ae8-45a7-b2d9-57afb84f28ca
```

```yaml
# product.yaml
handle: product_id
  field:
    type: text
    placeholder: '{{ id }}'
```

In this example, the user can optionally define a `product_id`, if he doesn't want to use the content's ID. The placeholder will show him the content's ID as a starting point.
