### ISSUE TITLE
Set view model for specific blueprints

### ISSUE THREAD

**Issue by RobertCordes** [statamic/ideas#326]
The documentation only gives one example of where to specifiy your view model — inside a collection by using `inject`:

```yaml
# content/collections/pages.yaml
title: Pages
...
inject:
  view_model: App\ViewModels\Page
```
And that works as expected. In my pages collection I have different blueprints, for example `homepage.yaml`, `about.yaml`, etc. I’m expecting that I can just as well define view models inside those files:

```yaml
# resources/blueprints/collections/pages/homepage.yaml
title: Homepage
inject:
  view_model: App\ViewModels\Home

# or

title: Homepage
view_model: App\ViewModels\Home
```
Reading the [documentation on view models](https://statamic.dev/view-models), I didn't expect this to be a problem. I also tried using [YAML front matter](https://statamic.dev/variables#view-frontmatter) inside the template:

```yaml
# resources/views/home.antlers.html
---
view_model: App\ViewModels\Home
---
<div>...</div>
```

What **does work** however is defining the view model inside the markdown files:
```yaml
# content/collections/pages/de/home.md
---
title: Homepage
template: home
view_model: App\ViewModels\Home
...
```

But I think you should be able to define the view model for specific blueprints inside the yaml file.
