### ISSUE TITLE
Default values for fields

### ISSUE THREAD

**Issue by eldor** [statamic/ideas#356]
Isn't it possible to set a default value for fields on blueprints?
Thanks in advance

**Comment by damcclean** [comment]
FYI, This can already been done but you need to do it from inside the blueprint's file, not through the blueprint builder in the Control Panel.

However, I think it is planned to add it to the blueprint builder as well, as that would make sense.

```
 -
        handle: description
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          type: markdown
          localizable: false
          listable: hidden
          display: Description
          default: something
```
