### ISSUE TITLE
Restrict template field to folder(s)

### ISSUE THREAD

**Issue by freshface** [statamic/ideas#367]
You can now show/hide the partials in the template dropdown.
But it would be nice to only load the content of a defined folder or folders (like the asset field)

**Comment by jasonvarga** [comment]
In these situations we suggest that you just create a `select` field with the options you actually want.

```yaml
handle: template
field:
  type: select
  options:
    folder/this_template: 'This Template'
    folder/that_template: 'That Template'
```
