### ISSUE TITLE
Be able to `slug` any text field

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#37]
I have found myself needing a "slug" field based on another field (not the title). Would be great if we could "attach" the slug to a text field.

**Comment by schwartzmj** [comment]
Generating a GUID or even incrementing a number would fulfill my need

**Comment by jasonvarga** [comment]
```yaml
fields:
  -
    handle: text
    field:
      type: slug
      from: not_the_title
```
