### ISSUE TITLE
Customizing Listing Columns like in v2

### ISSUE THREAD

**Issue by marcusand** [statamic/ideas#378]
In version 2 there was this: https://v2.statamic.com/control-panel#customizing-listing-columns

I would really like to see something similar in v3. 
So being able to set the configuration globally and not only per user and more importantly being able to have more config options. For example right now, if you choose to have an image column, clicking that image will open the img url rather than the editor view of the entry. I would really like to change that. 

Thanks! :)

**Comment by edalzell** [comment]
My use case is that we'd like to have some default columns, in a particular order shown in the CP.

**Comment by FrittenKeeZ** [comment]
I have the same wish as @edalzell since we used that quite a lot in v2.
Most users of v3 have no clue how to set columns manually, and are confused as to why they need to specify the columns instead of having defaults shown.

**Comment by jelleroorda** [comment]
@FrittenKeeZ You can set the default columns yourself though, in your blueprints, for the field you can add the `listable` field.

From the top of my head:
- `listable: false` To hide the column from the overview entirely (not selectable through customization).
- `listable: true` To make the column visible by default
- `listable: hidden` To make the column hidden by default,  users can still view through customization.

Example:
```yaml
      -
        handle: title
        field:
          input_type: text
          type: text
          icon: text
          listable: hidden
          validate:
            - string
```

**Comment by FrittenKeeZ** [comment]
@jelleroorda problem is you can't control the order of the columns or how they are formatted.

**Comment by jelleroorda** [comment]
@FrittenKeeZ Yes, that's true. You mentioned users don't know how to do it manually; so I thought you might not know about how to enable the proper default columns for your users.

**Comment by FrittenKeeZ** [comment]
I also just noticed that `section` fieldtypes occur in the possible columns list as well, which doesn't quite make any sense, since they don't provide any content.

**Comment by duncanmcclean** [comment]
Statamic allows you to configure "default preferences" which will apply to all users - this allows you to configure the columns & the order those columns are shown by default in the listing tables.

Here's the easiest way of setting default preferences for a collection's listing table:

1. Go to the relevant collection in the Control Panel and use the 'column picker' to configure the columns & the order of the columns.
2. Once you're happy, go to your user's YAML file. You'll see a `preferences` key containing the columns you just configured:

```yaml
preferences:
  collections:
    articles:
      columns:
        - title
        - date
        - status
```

3. Create a new `resources/preferences.yaml` file & copy everything inside of the `preferences` key into that file so it looks like this:

```yaml
collections:
  articles:
    columns:
      - title
      - date
      - status
```

4. Now, when you login as another user, they'll be using the default columns you just configured. 

_^ These steps assume you're using flat file users. If you're using database users, you'll need to [convert the JSON preferences data from your `users` table to YAML](https://json2yaml.com/)._

Of course, users can still override the default columns if they wish using the 'column picker' which lets them select any of the listable fields in the collection's blueprint.

I'll keep this open as we may add a way to set default columns in the column picker in the future, without needing to mess with YAML.
