### ISSUE TITLE
Ability to set a default for the Select field type

### ISSUE THREAD

**Issue by DrTrills** [statamic/ideas#380]
It would be great to select a default from the select field type so the user doesn't need to specifically select an option in order for ii to load

**Comment by damcclean** [comment]
I think you can actually do this right now but you have to do it in the blueprint's YAML file. (there's not an option in the UI yet)

Here's a slimmed down version of what the select field would look like with the `default` setting. The value should be a key of one of your select options.

```
choose_something:
  field:
    type: select
    default: a_select_key
```

This issue is a duplicate of #356.
