### ISSUE TITLE
Finer grained permissions on field level in blueprints

### ISSUE THREAD

**Issue by jelleroorda** [statamic/ideas#399]
Right now I have a few use cases where users of the site have to work together to publish content. So basically there is someone who will fill out the content, and then there’s someone who “checks” the content and updates a feedback field if the content needs improvements. Right now I have to create a custom EntriesController that basically does the same as the core EntriesController, but then adds/removes `read_only: true` from the specific fields. It would be rad if you could simply specify something along the lines of:

```yaml
- handle: feedback
  type: textarea 
  policy: ‘my custom registered permission’
```

Which would be the simple case I described above, or maybe also allow an optional more fine grained control:

```yaml
- handle: feedback
  type: textarea 
  policy:
    read: ‘my custom registered permission’
    edit: ‘another permission’
```

Other than it being a conditional read_only field (or not having it shown in the CP at all) it would of course filter out these fields on store/update.
