### ISSUE TITLE
Enhance Replicator/Bard Localization

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#439]
As of now, Replicator and Bard fields can only be localized at the top-level. It would be totally awesome to be able to configure localization on set fields instead. I'm running into this issue on every multi-site. I'm aware that this probably means a major refactor of how multi-sites work.

**Comment by jasonvarga** [comment]
One big hurdle I see with this is how to store a single nested localized field's value.

We could probably give each Replicator/Bard/Grid set/row an ID, then the localized version could reference that somehow. I still don't really know what that would look like in YAML. Maybe something like this?

```yaml
replicator:
  -
    id: 123
    type: quote
    quote_text: Hello!
    quote_author: John Smith
  -
    id: 456
    type: photo
    image: foo.jpg
```

```yaml
replicator:
  123:
    quote_text: Bonjour!
```
