### ISSUE TITLE
Create slug from multiple fields

### ISSUE THREAD

**Issue by byron-roots** [statamic/ideas#532]
I have an event collection where a lot of the events are repeated and therefore have the same name. This causes issues as we can't create the fields as the slug already exists elsewhere. I saw in issue #37 that you can change the field the slug is based on. Unfortunately this only allows to change the field and not add additional.

If we could add multiple fields to the from value that would be ideal, such as 
```
fields:
  -
    handle: text
    field:
      type: slug
      from: date title
```
