### ISSUE TITLE
Add ability to set names in form emails

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#536]
It would be great if we could also set the name for form emails. Something like this:

```yaml
to: '{{ email }}'
to_name: '{{ first_name }} {{ last_name }}'

from: jack@statamic.com
from_name: 'Jack McDade'

reply_to: jack@statamic.com
reply_to_name: 'Jack McDade'
```

**Comment by aerni** [comment]
Did a little source dive and it looks like this is already possible with the following syntax:

```yaml
to: '{{ first_name }} {{ last_name }} <{{ email }}>'
from: 'Jack McDade <jack@statamic.com>'
reply_to: 'Jack McDade <jack@statamic.com>'
```
