### ISSUE TITLE
Allow a field display label to be set to none

### ISSUE THREAD

**Issue by JayGeorge** [statamic/ideas#555]
It would be great to be able to set the 'Display' label of a field to nothing.

While the display name is usually desirable in certain situations it makes the admin UI look cluttered. A good example would be in the Replicator field, where it can sometimes be redundant and look like inception.

Here is an example where I have to give the Display label but it's undesirable:
<img width="878" alt="Screenshot 2021-05-24 at 11 36 29" src="https://user-images.githubusercontent.com/693601/119387430-d8161280-bcc0-11eb-8007-bcd6e64bf037.png">

**Comment by duncanmcclean** [comment]
Have you tried `replicator_preview: false` on the replicator field?

**Comment by JayGeorge** [comment]
Oh I didn't realise that option existed. Having said that, I've just tried this and I'm not sure it has the desired effect. The video label still appears

Code below, if this is the correct place to use it:

```yaml
-
        handle: replicator
        field:
          collapse: false
          sets:
            video:
              display: Video
              replicator_preview: false
              fields:
                -
                  handle: video
                  field:
                    type: video
                    icon: video
                    listable: hidden
                -
                  handle: autoplay
                  field:
                    display: Autoplay
                    type: toggle
                    icon: toggle
                    listable: hidden
```
