### ISSUE TITLE
Parse tags in Blueprints

### ISSUE THREAD

**Issue by simonhamp** [statamic/ideas#590]
Here's what I want to achieve:

```yaml
user.email:
  if:
    use_authenticated: 'equals false'
  display: 'Committer email address'
  instructions:
    The email address to associate with commits made by Gitamic. Empty this field to use
    `{{ config:statamic:git:user:email }}` from `config/statamic/git.php`.
  type: text
```

Unfortunately, that `{{ config:statamic:git:user:email }}` doesn't get parsed, so instead of:

> The email address to associate with commits made by Gitamic. Empty this field to use
> `simon@example.com` from `config/statamic/git.php`.

the user would see:

> The email address to associate with commits made by Gitamic. Empty this field to use
> `{{ config:statamic:git:user:email }}` from `config/statamic/git.php`.

**Comment by JohnathonKoster** [comment]
I can see the use-cases and value of this - just thinking through it - would it be something best limited to just the `instructions` or `display` properties? I could see some interesting/hard-to-debug consequences of doing something like this with the type field (although, it would be kind of cool):

```
user.email:
  display: 'Field Display'
  instructions_antlers: true
  instructions:
    Some instructions
    `{{ config:statamic:git:user:email }}`
  type_antlers: true
  type: '{{ stuff ? "integer" : "text" }}'
```
