### ISSUE TITLE
Add `read_only` toggle to blueprint field config in the control panel

### ISSUE THREAD

**Issue by johncarter-** [statamic/ideas#761]
Currently is available to manually set in the `blueprint.yaml`:
```yaml
      -
        handle: whatever
        field:
          read_only: true
```

It would be nice to have the option in the control panel's blueprint field config UI to save having to edit the blueprint directly.

See https://discord.com/channels/489818810157891584/489819906540568593/948240507476279337
