### ISSUE TITLE
More flexibility in nested field conditions

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/ideas#783]
### Bug description

**This probably isn't a bug. Let me know if I should move it to ideas.**

I have a complicated page builder replicator:

- Sections (replicator)
  - Full Section (fieldset)
    - Blocks (replicator)
      - Card Group (fieldset) 
        - Style (field)
        - Items (replicator)
          - Link (field)
          - Icon (field)

I am trying to use field conditions to toggle the card_group.items fields, like so:

```
handle: link
if:
  card_group.style: 'linked'

handle: icon
if:
  card_group.style: 'iconed'
```

The above doesn't work. I have also tried `root.style` but I think root targets the top-level 'Sections' replicator.

### How to reproduce

See above.

### Versions

Statamic 3.3.7 Solo
Laravel 8.83.8
PHP 8.1.1
edalzell/blade-directives 3.7

### Installation

Fresh statamic/statamic site via CLI
