### ISSUE TITLE
Make labels of array field type available in templates

### ISSUE THREAD

**Issue by klickreflex** [statamic/ideas#825]
It is impossible to render the labels defined on a keyed array field in templates. 

Assume the following field:

```yaml
handle: stakeholders
  field:
    mode: keyed
    keys:
      visualisierung: Visualisierung
      freiflaechenplanung: Freiflächenplanung
```

We can iterate over keys and values in antlers:
```antlers
{{ foreach:stakeholders }}
  {{ key }}
  {{ value }}
{{ /foreach:stakeholders }}
```

However, there is no way to render the label in templates (e.g. showing the labels _Visualisierung_ and _Freiflächenplanung_ instead of the keys _visualisierung_ and _value_.
