### ISSUE TITLE
Generate slug from multiple fields

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#938]
I think it would be a nice feature if we could generate the slug from multiple fields. Similar to how we can already do it with the [title format](https://statamic.dev/collections#titles) of collection entries.

In this example, I want to generate the slug from the entry's title and date:

```yaml
handle: slug
field:
  type: slug
  from: '{title} {date}'
```
