### ISSUE TITLE
allow to specify a specific entry for entry field type instead of a whole collection

### ISSUE THREAD

**Issue by videni** [statamic/ideas#994]
Can we specify a specific entry for entry field type instead of a whole collection?

## tile blueprint

```yaml
  - field:
      icon: entries
      mode: default
      type: entries
      create: true
      display: Manufacturer
      listable: hidden
      max_items: 1
      visibility: visible
      collections:
      - ceramics:manufacturer  #  manufacturer is another blueprint in the same collection `ceramics` ,
      # I don't want the blueprint can select itself(tile) as a manufacturer
      hide_display: false
      instructions_position: above
    handle: manufacturer
```
